# Generated by Django 3.2.9 on 2021-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Efectivo'), (1, 'Tarjeta de crédito'), (2, 'Tarjeta de débito')], default=0, verbose_name='Método de pago'),
        ),
    ]
